### ISSUE TITLE
Error when I set allocate_tod=False

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#114]
Hi @ziotom78 and @dpole, 
I get `AttributeError: 'Observation' object has no attribute 'tod'`
in `setattr_det_global` when I set allocate_tod=False with more than one mpi task active.
If I comment this line https://github.com/litebird/litebird_sim/blob/5beb93a552a4ba41b6c259707be27b6c8db8cf55/litebird_sim/observations.py#L514
or if I only use one mpi task the run goes smooth

**Comment by dpole** [comment]
Right, I see the problem. We should decide whether the a non allocated tod should be `obs.tod` missing or `obs.tod = None`. That line assumes the former but apparently the code above assumes the latter. Preferences? @ziotom78 ?

**Comment by ziotom78** [comment]
> Right, I see the problem. We should decide whether a non-allocated tod should be obs.tod missing or obs.tod = None. That line assumes the former but apparently the code above assumes the latter. Preferences? @ziotom78 ?

I would prefer to have `obs.tod = None`, as I find much easier to write/read

```python
if obs.tod:
    # …
```

than

```python
if hasattr(obs, "tod"):
    # …
```

**Comment by dpole** [comment]
Note however that the former need to to be `if obs.tod is not None` to work also when `tod` is an array

**Comment by dpole** [comment]
It seems still preferable to me

**Comment by ziotom78** [comment]
> It seems still preferable to me

I agree!

**Comment by dpole** [comment]
Please @paganol have a look at this PR, it should fix the issue

**Comment by paganol** [comment]
Perfect. Thanks!
