### ISSUE TITLE
Units in litebird_sim

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#119]
We should treat uniformly the units in the code. Currently, mbs produces maps in uK. The noise generation module adds to the TOD noise in K. It takes sigma_uk and converts it to K. @unfunfunt @ziotom78 Should we add an option to handle this?

@NicolettaK, is mbs able to handle the units internally?

**Comment by ziotom78** [comment]
Noise generation has been fixed by #120 . Still waiting to fix `Mbs`.

**Comment by ziotom78** [comment]
@NicolettaK , what do you think about changing the default unit for `Mbs` from µK to K? Do you think it is feasible, or would it be too disruptive for existing codes?

**Comment by NicolettaK** [comment]
Ciao, sorry for the late reply...I thought mbs was able to handle units actually! I check that and let you know. Anyway if you prefer K as default it should be doable.

**Comment by NicolettaK** [comment]
This has been addressed in https://github.com/litebird/litebird_sim/pull/123
