### ISSUE TITLE
Extend the API to access the IMO

### ISSUE THREAD

**Issue by ziotom78** [litebird/litebird_sim#142]
Currently, the classes `Imo` and `ImoFlatFile` implement a basic API to access the IMO. However, there are several other higher-level functions and classes that would be useful in the code:

- A set of functions to easily navigate through the tree of entities (currently this is possible but requires a good knowledge of the internals of the way the `Imo` class works).
- The ability to quickly access data files: so far the classes only provide access to the *metadata* in the IMO (i.e., the numbers saved directly in the JSON file).
- A `ImoWebConnection` class that uses RESTful API to query a remote database. This is surely not something we want to use in full-scale simulations, but it might be useful for codes that want to check if the remote database has a newer copy of the objects used in a simulation and warn the user about it.
- Possibly, a more performant way to convert paths like `/satellite/LFT/…` into proper UUIDs (e.g., using a memory database instead of doing string concatenation every time).

**Comment by unfunfunt** [comment]
Working on the exercise at the working meeting in Japan, I would love some sort of wildcard function for the imo if that was technically feasible. My objective would be to do something like this (although maybe this is a dumb thing to want to do):

imo=lbs.Imo()
detlist = []

LFT_40_dets = imo.query("/releases/v1.3/satellite/LFT/L1-040/*/detector_info") #returns a list
for det in LFT_40_dets:
   detInfo = lbs.DetectorInfo.from_imo(
      imo=imo,
      url=det,
   ) 
   detlist.append(detInfo)
 #makes a list of DetectorInfo, one for each detector in L1-040

**Comment by marcobortolami** [comment]
Hi @unfunfunt ,
I think that what you want to do can be done just by looping over the `channelinfo.detector_names` field :) I prepared a small code for doing this:
```
import litebird_sim as lbs

instrument = 'LFT'
channel    = 'L1-040'

imo = lbs.Imo()

channel_info = lbs.FreqChannelInfo.from_imo(
	url="/releases/v1.3/satellite/"+instrument+"/"+channel+"/channel_info",
	imo=imo,
)

print(channel_info,'\n')

det_list = []

for det_name in channel_info.detector_names:
	det_list.append(lbs.DetectorInfo.from_imo(
			url='/releases/v1.3/satellite/'+instrument+'/'+channel+'/'+det_name+'/detector_info',
			imo=imo,
		)
	)

print(len(det_list),'\n')
print(det_list[0])
```
I suggest you to have a look at the output, to see what's inside the channel and detector info objects:)

**Comment by ziotom78** [comment]
This is done by #282
