### ISSUE TITLE
ERROR: Failed building wheel for ducc0

### ISSUE THREAD

**Issue by AleNovelli** [litebird/litebird_sim#144]
Hi, I don't know if this is appropriate here or if I should post this in [litebird/ducc](https://github.com/litebird/ducc), let me know if I should move it.

- **OS version:** Virtual machine running Ubuntu 20.04.3 LTS on a Windows 10 host
- **Python:** Python 3.8.12
- **Pip:** pip 21.3.1 

I am encountering an error while installing litebird_sim in my conda virtual environment:
`pip install litebird_sim`

Error message:
```
  Building wheels for collected packages: ducc0
  Building wheel for ducc0 (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/alessandro/anaconda3/envs/lbs_env/bin/python /home/alessandro/anaconda3/envs/lbs_env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpt6d94sjh
       cwd: /tmp/pip-install-h__aiq0q/ducc0_19030a5b847542598b13700d2d830ca2
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ducc0' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/python
  gcc -pthread -B /home/alessandro/anaconda3/envs/lbs_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPKGNAME=ducc0 -DPKGVERSION="0.8.0" -I. -I./src/ -I/tmp/pip-build-env-1nemk_1q/overlay/lib/python3.8/site-packages/pybind11/include -I/tmp/pip-build-env-1nemk_1q/overlay/lib/python3.8/site-packages/pybind11/include -I/home/alessandro/anaconda3/envs/lbs_env/include/python3.8 -c python/ducc.cc -o build/temp.linux-x86_64-3.8/python/ducc.o -std=c++17 -g0 -ffast-math -O3 -march=native -Wfatal-errors -Wfloat-conversion -W -Wall -Wstrict-aliasing=2 -Wwrite-strings -Wredundant-decls -Woverloaded-virtual -Wcast-qual -Wcast-align -Wpointer-arith
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
  compilation terminated due to -Wfatal-errors.
  error: command 'gcc' failed with exit status 1
  ERROR: Failed building wheel for ducc0
 
Failed to build ducc0
ERROR: Could not build wheels for ducc0, which is required to install pyproject.toml-based projects
```

if I run:
`python -m pip install --upgrade pip setuptools wheel`
everything seems in order:
```
Requirement already satisfied: pip in ./anaconda3/envs/lbs_env/lib/python3.8/site-packages (21.3.1)
Requirement already satisfied: setuptools in ./anaconda3/envs/lbs_env/lib/python3.8/site-packages (58.4.0)
Requirement already satisfied: wheel in ./.local/lib/python3.8/site-packages (0.37.0)
```

In particular, this error only happens if I try to install version 0.8.0 or previous of ducc0.
If, instead I try to run `pip install ducc0`
it successfully installs version 0.21.0
```
Collecting ducc0
  Using cached ducc0-0.21.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Requirement already satisfied: numpy>=1.17.0 in ./anaconda3/envs/lbs_env/lib/python3.8/site-packages (from ducc0) (1.21.3)
Installing collected packages: ducc0
Successfully installed ducc0-0.21.0
```

Can anybody give me some pointers about what the problem might be?

**Comment by mreineck** [comment]
I think the reason is that `ducc0` 0.8 still had a pretty bad build machinery. This package is definitely obsolete now and should be replaced by something newer. Does `litebird_sim` have a hardwired dependency on `ducc0` 0.8? If so, I'd propose to update this.

Still, I don't understand how this line happens:
> `cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch`
 
There should be no mention of a particular architecture in the `ducc0` sources, so where is this coming from?

**Comment by AleNovelli** [comment]
Hi, I solved the problem by updating `gcc` and `g++` to version 10 (I did not realize the virtual machine did not have the latest version).
Once I did that I was able to install version 0.8.0 of `ducc0` and finish the installation of `litebird_sim`

Thank you a lot for your help
