### ISSUE TITLE
Implement a basic map maker

### ISSUE THREAD

**Issue by ziotom78** [litebird/litebird_sim#15]
We're surely going to incorporate full-fledged solutions, like [libmadam](https://github.com/hpc4cmb/libmadam) or [TOAST](https://github.com/hpc4cmb/toast) , but as a start we should implement a simple binning algorithm, to test the interface with `Simulation` objects.

**Comment by mreineck** [comment]
If you like, you could use `ducc0.healpix` functionality for the pixel-related calculations. Please let me know if I can help with this!

**Comment by ziotom78** [comment]
Work is ongoing in the [`bin_map_maker`](https://github.com/litebird/litebird_sim/tree/bin_map_maker) branch.

**Comment by ziotom78** [comment]
This was implemented by PR #73 .
