### ISSUE TITLE
Dipole in the map based simulations

### ISSUE THREAD

**Issue by ClementLeloup** [litebird/litebird_sim#226]
Hello,

I would need, and probably this would be useful to other people as well, a function to produce a map that include the CMB dipole at the map-level but it appears that it's not yet implemented in MBS. It might be an interesting addition for those who don't need to go through the whole pipeline of TODs simulations and mapmaking, and not very difficult to implement.
Cheers

**Comment by paganol** [comment]
Hi @ClementLeloup, I've added this feature in #227. Let me know if it is what you need. For now only `DipoleType.LINEAR` has been implemented, if you need more refined approximations, with frequency dependent terms, can be easily added.
