### ISSUE TITLE
Importing vs incorporating libraries

### ISSUE THREAD

**Issue by dpole** [litebird/litebird_sim#25]
We should have a general discussion and, possibly, guidelines about how to interface with the existing libraries that we want to plug in the pipeline. In particular, we should decide when add them as a dependency and import them and when we move them inside litebird_sim continue the development here.

Here is a proposal

## Import when
* it is a general purpose library developed independently from the simulation team

## Integrate when
* only a small and stable piece of a complex library is needed
* the main case of use of the library is the LiteBIRD pipeline or LiteBIRD-related activities

**Comment by dpole** [comment]
To make a concrete example, I was asked to include `fgbuster`. I think it should be included as a dependency because it is currently being applied in many contexts outside LiteBIRD.

**Comment by ziotom78** [comment]
Hi @dpole, I agree with you, integrating codes would place additional burden on our shoulders and should be done only in particular cases. Importing libraries should generally be the way to go; of course, in this case we should ensure that the library can be installed using `pip`: if it's in the [PyPI](https://pypi.python.org/), we can just add the dependency to `pyproject.toml` and the installation will be a breeze.

I think we can use this issue to track which libraries we want to use in this repo, and to decide which approach to use with each. Currently, the libraries we plan to use are the following:

- [TOAST](https://github.com/hpc4cmb/toast);
- [ForeGroundBuster](https://github.com/fgbuster/fgbuster) or any other component separation code;
- [pyinterpol_ng](https://gitlab.mpcdf.mpg.de/mtr/cxxbase/-/tree/master/pyinterpol_ng).

I believe that all of three fall in the `import` category. Others?

**Comment by ziotom78** [comment]
I believe this issue can be closed: we have settled upon importing everything, and we have devised a schema to use libraries that have been installed by the user (mpi4py, TOAST) which seems to wok.
