### ISSUE TITLE
Update pysm3 to the latest version

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#253]
We should update pysm3 to the latest version and update the models as well.

**Comment by ziotom78** [comment]
I just opened PR #254, which bumps the dependencies on NumPy (getting rid of an old dependabot warning), AstroPy, and PySM3 among others.

**Comment by ziotom78** [comment]
This should have been solved now that PR #254 has been merged, as `pyproject.toml` now lists version 3.3.2, which is the [most recent version](https://pypi.org/project/pysm3/) available on PyPI. Feel free to reopen it if the issue was not solved!
