### ISSUE TITLE
Bandpass information not passed to mbs

### ISSUE THREAD

**Issue by sgiardie** [litebird/litebird_sim#269]
In mbs there should the possibility to pass a bandpass to use in band integration. The instrument information are passed through the [_InstrumentFreq](https://github.com/litebird/litebird_sim/blob/2fe793dc1ca257f817f41c02f75a390bcbbf4007/litebird_sim/mbs/mbs.py#L22) class. Though, in the methods below, like the [one to pass a dictionary](https://github.com/litebird/litebird_sim/blob/2fe793dc1ca257f817f41c02f75a390bcbbf4007/litebird_sim/mbs/mbs.py#L36), the `band` attribute is automatically set to `None`. If we set it to `dictionary["band"]` instead it works. Should that line and the ones below (47 and 58) be fixed?

**Comment by ziotom78** [comment]
Absolutely! I missed that, please update `.from_dict` as you said. Thanks!

**Comment by ziotom78** [comment]
I believe that PR #271 fixed this issue. @sgiardie I'm closing it, if you think it's wrong feel free to reopen it!
