### ISSUE TITLE
Integrating the convolution/interpolation code into the repository

### ISSUE THREAD

**Issue by mreineck** [litebird/litebird_sim#31]
Since `litebird_sim` will most likely be the heaviest user of this new library in the near future, it makes a lot of sense to have at least a fork of the code withing the `litebird` Github organization, so I plan to add the code soon.
Technical question: does it make more sense to provide it as a standalone repository within https://github.com/litebird/, or should it be a subtree of https://github.com/litebird/litebird_sim/?
@ziotom78 what do you think?

**Comment by ziotom78** [comment]
By «subtree» you just mean a folder within litebird_sim, right? For me this solution is ok, it means that we bundle everything together, which is probably the easiest way to go.

**Comment by mreineck** [comment]
> By «subtree» you just mean a folder within litebird_sim, right?

Exactly.

> For me this solution is ok, it means that we bundle everything together, which is probably the easiest way to go.

Absolutely fine. I just wanted to double-check, as this code is not so much a "module", but rather a library that will be imported by other modules.

**Comment by dpole** [comment]
I'd only recommend to add an intermediate generic folder e.g. beam_convolution and put the code inside a subfolder. This way we can maintain the same structure even if we add another module related to beam convolution.

I only see two pros in keeping the code outside of the repo. 
* The history of your module would be cleaner.
* If the installation is not trivial and we have many such modules, the files managing the install could become complicated.

**Comment by mreineck** [comment]
I'll open a pull request, and then we can discuss the concrete placement there, OK?

**Comment by NicolettaK** [comment]
I agree to have it in a sub folder. I’ll do the same for the map based sims. And this is something we should put in the guidelines.

**Comment by mreineck** [comment]
It was agreed in #32 to provide this functionality as a separate package within the `litebird` Github organization. This is done now in the form of https://github.com/litebird/ducc.

**Comment by ziotom78** [comment]
Awesome! I checked on an empty Poetry project, the dependency can be added to `pyproject.toml` using

```
poetry add git+https://github.com/litebird/ducc.git#ducc0
```

and then running `poetry install`. Nothing else is required.

**Comment by mreineck** [comment]
That's really beautiful! You can probably even remove the `#ducc0` part, since this is the default branch, but I'm not sure.

**Comment by ziotom78** [comment]
No, I tried and it fails, as it looks for the `master` branch.

**Comment by mreineck** [comment]
Weird. But not a big deal, I suppose :)

Currently there is no CI for the `ducc` repository, since it is tailored for our Gitlab environment. I'll see if I can come up with something.
