### ISSUE TITLE
Incorrect data download from IMO

### ISSUE THREAD

**Issue by nraffuzz** [litebird/litebird_sim#317]
I'm using a script to generate an observation and while loading the definition of the instrumen
```
sim.set_instrument(
    lbs.InstrumentInfo.from_imo(
        imo,
        f"/releases/{imo_version}/satellite/{telescope}/instrument_info",
    )
)
```

I get this error:
```
InstrumentDbFormatError                   Traceback (most recent call last)
[...]
InstrumentDbFormatError: You do not seem to have downloaded data files, only the schema file
```

The same error happens while using the available IMO version present in litebird_sim (`imo = lbs.Imo(flatfile_location=lbs.PTEP_IMO_LOCATION)`) and the full IMO (`imo = lbs.Imo()`, I tried the master and the v1.3 branches). The same happens while running the example notebooks here.

**Comment by ziotom78** [comment]
Hi @nraffuzz , thanks for the report! You're right, there was a bug in Libinsdb. I have published a new patch release (0.7.4)  and have update the dependency, might you please check that PR #318 fixes the issue?
