### ISSUE TITLE
Possible reorganization of the documentation

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#341]
The current version of the documentation is a bit messy, here are some suggestions we can implement to improve readability:
1. the scanning strategy chapter is rather long, we could move the hwp (and in general the pointing generation) in a new entry;
2. the chapter `Time order simulations` could be converted simple page with a general introduction and then links to single pages for dipole, scan map, noise, and (in the future) beam convolution.
3. all the systematics (non linearity, gain drift, hwp systematics, etc..) could go in a single separate chapter 
4. the entry Bandpasses could go in a sub entry of the chapter `Detectors, channels, and instruments`

**Comment by anand-avinash** [comment]
If easily doable, I would suggest also to change the documentation theme. With the current theme I find it very difficult to navigate and infer the type, default values, etc. of the function arguments from the documentation. One such example:
![image](https://github.com/user-attachments/assets/2eb2fddd-ea2c-4664-812e-35c09a3a5f6a)

**Comment by ziotom78** [comment]
Hi @anand-avinash , I agree, the look is terrible!

Do you have any example of a good alternative for our Sphinx theme? I have little experience in customizing Sphinx.

**Comment by anand-avinash** [comment]
To me, PyData sphinx theme looks better. It is the same theme used by numpy and scipy docs
https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/gallery.html

**Comment by yusuke-takase** [comment]
I tried to change a document of my [grasp2alm](https://yusuke-takase.github.io/grasp2alm/index.html#) `alabaster` (current lbsim's docs theme) to `pydata_sphinx_theme`, indeed it looks better and it was not too difficult.

**Comment by ziotom78** [comment]
Hi all, thanks for your comments! I can work on this.

I am currently thinking of a possible way to get a reasonable outline for the manual. What do you think about the following structure?

![image](https://github.com/user-attachments/assets/87840afe-bb32-46e2-8f0a-69c2a8751205)
