### ISSUE TITLE
Pointing and polarization angle

### ISSUE THREAD

**Issue by dpole** [litebird/litebird_sim#36]
Mapmaking requires information about the detector pointing and polarization angle. Have we defined how this information can be retrieved? Sorry if I missed

**Comment by dpole** [comment]
#15

**Comment by ziotom78** [comment]
That's a good point. In the code I've used in the past, I have always stored the three angles theta, phi, and psi (colatitude, longitude, orientation), possibly using float32 types to save memory. Are there other options?

**Comment by mreineck** [comment]
My idea of an optimal implementation would be the following:
- the only pointing data that's actually stored any where are satellite orientation quaternions, sampled at a very low frequency (well below 1Hz should be enough)
- from that it is (in principle) straightforward and fast to compute detector quaternions at any desired frequency, and (theta,phi,psi) triples from that, if required. So all that's needed is a function which performs exactly this job (see #10).

This should be very economic in both space and time.

**Comment by ziotom78** [comment]
@mreineck , you're right, I forgot about that discussion.

**Comment by dpole** [comment]
I think that #48 addressed this issue. @ziotom78 , right?

**Comment by ziotom78** [comment]
Yes, I believe we can close this issue now.
