### ISSUE TITLE
using MPI

### ISSUE THREAD

**Issue by NicolettaK** [litebird/litebird_sim#45]
I'm trying to implement parallelization in the `Mbs` class. I can't enable `mpi4py` though. 
I've followed the instruction here: https://github.com/litebird/litebird_sim/blob/master/docs/source/mpi.rst and set the environment variable with `export LITEBIRD_SIM_PI=1`, however `lbs.MPI_ENABLED ` is still `False` and I don't get any error (which I think I should get as if I do `import mpi4py` it doesn't work)

**Comment by dpole** [comment]
Could it be just a typo (export `LITEBIRD_SIM_*M*PI=1`)?

**Comment by NicolettaK** [comment]
That was actually a smart guess @dpole :-D! 
Now I got the error I expected! We do not want to add `mpi4py` as dependency in poetry?

**Comment by dpole** [comment]
I wish all my bugs were so quick to find :) 
About the dependency, did you install litebird_sim with `--extras=mpi`?

**Comment by dpole** [comment]
@NicolettaK , do you think we can close the issue?
