### ISSUE TITLE
Compilation fails with intel compiler

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#52]
I'm having problems in the installation with the intel compiler 2018. The issue seems to be with ducc. Probably worth opening an issue also there. 
gcc 7.3.0 goes smooth, instead
Here the log

  - Installing ducc0 (0.4.0 d86009e)

[EnvCommandError]
Command ['/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/pip', 'install', '--no-deps', '-U', '-e', '/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0'] errored with the following return code 1, and output: 
Obtaining file:///galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Installing collected packages: ducc0
  Running setup.py develop for ducc0
    Complete output from command /galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/python -c "import setuptools, tokenize;__file__='/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing ducc0.egg-info/PKG-INFO
    writing dependency_links to ducc0.egg-info/dependency_links.txt
    writing requirements to ducc0.egg-info/requires.txt
    writing top-level names to ducc0.egg-info/top_level.txt
    reading manifest file 'ducc0.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.'
    writing manifest file 'ducc0.egg-info/SOURCES.txt'
    running build_ext
    building 'ducc0' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/python
    icc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPKGNAME=ducc0 -DPKGVERSION="0.4.0" -I. -I./src/ -I/tmp/pip-build-env-w12ypczt/overlay/lib/python3.7/site-packages/pybind11/include -I/tmp/pip-build-env-w12ypczt/overlay/lib/python3.7/site-packages/pybind11/include -I/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/include -I/cineca/prod/opt/tools/anaconda/2019.07/python--3.6.4/include/python3.7m -c python/ducc.cc -o build/temp.linux-x86_64-3.7/python/ducc.o -std=c++17 -march=native -ffast-math -O3 -Wfatal-errors -Wfloat-conversion -W -Wall -Wstrict-aliasing=2 -Wwrite-strings -Wredundant-decls -Woverloaded-virtual -Wcast-qual -Wcast-align -Wpointer-arith
    icc: command line warning #10006: ignoring unknown option '-Wfloat-conversion'
    icc: command line warning #10006: ignoring unknown option '-Wredundant-decls'
    icc: command line warning #10006: ignoring unknown option '-Wcast-align'
    In file included from python/ducc.cc(3):
    ./src/ducc0/infra/threading.cc(343): error: identifier "rethrow_exception" is undefined
          rethrow_exception(ex);
          ^
    
    compilation aborted for python/ducc.cc (code 4)
    error: command 'icc' failed with exit status 4
    
    ----------------------------------------
Command "/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/python -c "import setuptools, tokenize;__file__='/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/
You are using pip version 19.0.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by mreineck** [comment]
Thanks for the report!
In general I wouldn't expect the code to work with any Intel compiler, as they seem to have really bad C++17 support, but this particular problem is most likely genuine.

What's the best way to provide you with a tentative fix? Would a temporary `ducc` branch in the git repo be useful?

I'd be happy to test the code myself with the Intel compilers, but I don't have them on my private machines, and the installation at MPA is subtly broken ...

**Comment by dpole** [comment]
> I'd be happy to test the code myself with the Intel compilers, but I don't have them on my private machines, and the installation at MPA is subtly broken ...

FYI, Intel compilers are available (but not default) at NERSC

**Comment by mreineck** [comment]
Unfortunately my account there expired quite some time ago. But if really necessary I can probably reactivate it!

For now, I have pushed a fix that `poetry` should pick up if you try to build again. I expect you will get a bit farther, but I'd really be (pleasantly!) surprised if the compilation runs through.

**Comment by paganol** [comment]
here the new error 

[EnvCommandError]
Command ['/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/pip', 'install', '--no-deps', '-U', '-e', '/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0'] errored with the following return code 1, and output: 
Obtaining file:///galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Installing collected packages: ducc0
  Found existing installation: ducc0 0.4.0
    Uninstalling ducc0-0.4.0:
      Successfully uninstalled ducc0-0.4.0
  Running setup.py develop for ducc0
    Complete output from command /galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/python -c "import setuptools, tokenize;__file__='/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing ducc0.egg-info/PKG-INFO
    writing dependency_links to ducc0.egg-info/dependency_links.txt
    writing requirements to ducc0.egg-info/requires.txt
    writing top-level names to ducc0.egg-info/top_level.txt
    reading manifest file 'ducc0.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.'
    writing manifest file 'ducc0.egg-info/SOURCES.txt'
    running build_ext
    building 'ducc0' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/python
    icc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPKGNAME=ducc0 -DPKGVERSION="0.4.0" -I. -I./src/ -I/tmp/pip-build-env-ci13kv8y/overlay/lib/python3.7/site-packages/pybind11/include -I/tmp/pip-build-env-ci13kv8y/overlay/lib/python3.7/site-packages/pybind11/include -I/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/include -I/cineca/prod/opt/tools/anaconda/2019.07/python--3.6.4/include/python3.7m -c python/ducc.cc -o build/temp.linux-x86_64-3.7/python/ducc.o -std=c++17 -march=native -ffast-math -O3 -Wfatal-errors -Wfloat-conversion -W -Wall -Wstrict-aliasing=2 -Wwrite-strings -Wredundant-decls -Woverloaded-virtual -Wcast-qual -Wcast-align -Wpointer-arith
    icc: command line warning #10006: ignoring unknown option '-Wfloat-conversion'
    icc: command line warning #10006: ignoring unknown option '-Wredundant-decls'
    icc: command line warning #10006: ignoring unknown option '-Wcast-align'
    In file included from ./src/ducc0/sharp/sharp.cc(33),
                     from python/ducc.cc(7):
    ./src/ducc0/math/fft1d.h(1833): warning #2196: routine is both "inline" and "noinline"
          template<typename T> DUCC0_NOINLINE void exec(Cmplx<T> c[], T0 fct, bool fwd) const
                               ^
    
    In file included from ./src/ducc0/sharp/sharp.cc(33),
                     from python/ducc.cc(7):
    ./src/ducc0/math/fft1d.h(1870): warning #2196: routine is both "inline" and "noinline"
          template<typename T> DUCC0_NOINLINE void exec(T c[], T0 fct, bool fwd) const
                               ^
    
    In file included from ./src/ducc0/sharp/sharp_internal.h(33),
                     from ./src/ducc0/sharp/sharp.cc(34),
                     from python/ducc.cc(7):
    ./src/ducc0/sharp/sharp.h(35): catastrophic error: cannot open source file "any"
      #include <any>
                    ^
    
    compilation aborted for python/ducc.cc (code 4)
    error: command 'icc' failed with exit status 4
    
    ----------------------------------------
  Rolling back uninstall of ducc0
  Moving to /galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/lib/python3.7/site-packages/ducc0.egg-link
   from /tmp/pip-uninstall-skn4v4nm/ducc0.egg-link
Command "/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/bin/python -c "import setuptools, tokenize;__file__='/galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /galileo/home/userexternal/lpagano0/.cache/pypoetry/virtualenvs/litebird-sim-k6pebD1r-py3.7/src/ducc0/
You are using pip version 19.0.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by mreineck** [comment]
Yep, this is now a genuine `icc` deficiency. Header `any` must be part of a C++17 standard library, see, e.g., https://en.cppreference.com/w/cpp/utility/any

**Comment by mreineck** [comment]
How do we proceed with this? I don't really have a way of fixing this on our side, Should I state explicitly in the `ducc` README that current Intel compilers don't have sufficient language support for this package?

**Comment by mreineck** [comment]
I managed successful compilation and testing with the "next generation" of Intel compilers (https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html). As far as I can tell, this will replace the traditional Intel compilers fairly soon.

Is this sufficient to close this issue?

**Comment by ziotom78** [comment]
Hi @mreineck, yes, I think so. Given that ducc employs recent C++ features, I guess that most of the people using it will need to keep their compilers updated. So it's ok for me to close this issue.

@paganol , do you agree?

**Comment by paganol** [comment]
Sure, for me we can close it. Thanks!

**Comment by mreineck** [comment]
Small update: I have now included automatic testing with the Intel OneAPI compiler for `ducc` using Github Actions, so we will know very quickly when things go wrong with this compiler.
