### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by mreineck** [litebird/litebird_sim#59]
I'm trying to install `litebird_sim` locally, but get:

```
martin@debian:~/codes/litebird_sim$ poetry install --extras=jupyter --extras=docs
/home/martin/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
The currently activated Python version 2.7.18 is not supported by the project (^3.6).
Trying to find and use a compatible version. 
Using python3 (3.8.5)
Creating virtualenv litebird-sim-p-FMZbmZ-py3.8 in /home/martin/.cache/pypoetry/virtualenvs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PosixPath' is not defined
Updating dependencies
Resolving dependencies... (4.4s)

[RuntimeError]
Unable to retrieve the package version for /tmp/pypoetry-git-ducc4GP15X
```

This used to work some time ago, and the Travis builds run as well, so I'm a bit at a loss what's going wrong here. Any ideas?

[Edit: add missing command line]

**Comment by mreineck** [comment]
Judging from open issues against `poetry`, this doesn't seem to be an isolated problem...

**Comment by ziotom78** [comment]
@mreineck , could you please post the output of the command

```
poetry debug
```

to check what's happening?

**Comment by mreineck** [comment]
Sure!

```
/home/martin/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

Poetry
Version: 1.0.10
Python:  2.7.18

Virtualenv
Python:         2.7.18
Implementation: CPython
Path:           NA

System
Platform: linux2
OS:       posix
Python:   /usr
```

`poetry` also seems to have some fixation on Python 2.7, but at least during installation it appears to switch to Python3 at some point.

**Comment by dpole** [comment]
Not sure it is safe nor of any help. I'd `poetry remove` your current environment (`poetry env info`) and try to `poetry install` from scratch. If it doesn't work, I'd try also to remove the lock file (which I forgot to add back in in my following commit, thanks @ziotom78 for doing that)

**Comment by mreineck** [comment]
OK, after nuking everything, the installation process seems to work again. Unfortunately I can't say what the original reason for the problem was :-( Thanks for your help!
