### ISSUE TITLE
from_imo method in the Instrument class

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#63]
Sould the Instrument class have a from_imo function? Something like the one we have for the Detector class

**Comment by ziotom78** [comment]
Absolutely! This is something I planned to do last week.

**Comment by paganol** [comment]
I can take care of that. In case, let me know.

**Comment by ziotom78** [comment]
Thanks, but I'm currently revising the way `Detector.from_imo` works, because PR #60 introduces the use of dataclasses, which make the implementation of this kind of feature trivial. Let's wait until I merge that PR.

**Comment by ziotom78** [comment]
Fixed in PR #60.
