### ISSUE TITLE
Add support for Python 3.8 in Travis

### ISSUE THREAD

**Issue by ziotom78** [litebird/litebird_sim#66]
Currently we're testing our codes against Python 3.6 and Python 3.7. As the default version installed by Anaconda is now 3.8, I think it would be worth to add it to the Travis build.

Not sure what to do with 3.7. If we keep 3.6 and add 3.8, is it worth to test an intermediate version? I fear the increase in the time required to complete a CI script.

(My experience with the Julia package ecosystem is that they always test the minimum compatible version and the most recent nominal version, and they always skip every version in-between.)

**Comment by dpole** [comment]
I agree with testing 3.6 and 3.8 only. The CI already takes quite a while.

**Comment by dpole** [comment]
Tests themselves are quick, installing takes most of the time. Shall we turn caching on?

**Comment by ziotom78** [comment]
@dpole , I don't know about caching. If you know how to do this, feel free to do it!!

**Comment by dpole** [comment]
Not sure I do....but I'll try! ;)

**Comment by ziotom78** [comment]
@dpole, perhaps using the syntax found here: https://docs.travis-ci.com/user/caching/#arbitrary-directories to specify the poetry cache directory:

```yaml
cache:
  directories:
    - $HOME/.cache/pypoetry
```

**Comment by dpole** [comment]
That is what I tried to do in the `ci_caching` branch, with no success...

**Comment by ziotom78** [comment]
@dpole , any good news about caching? If you want, I can take a look to your `ci_caching` branch.

**Comment by dpole** [comment]
Sorry for the late reply. Nope, I gave it a try but did not succeed

**Comment by ziotom78** [comment]
This is superseded by the adoption of GitHub Actions to run our CI builds instead of Travis. The new actions implemented in #77 test Python 3.8 on Linux systems.
