### ISSUE TITLE
Issue with make_bin_map and Observation class

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#78]
make_bin_map requires obs.pixel and obs.psi which are note defined properly.

    Args:
        obss (list of :class:`Observations`): observations to be mapped. They
            are required to have the following attributes as arrays of identical
            shapes
            * `tod`: the time-ordered data to be mapped
            * `pixel`: the index of the pixel observed for each tod sample in a
              HEALpix map at nside `nside`
            * `psi`: the polarization angle (in radians) for each tod sample

Actually obs.pixel contains the detector id in the wafer 

            det = lbs.DetectorInfo.from_imo(url="/releases/v1.0/satellite/MFT/M1-140/M03_030_QA_140T/detector_info",imo=imo)
            obs, = sim.create_observations(detectors=[det])
            print(obs.pixel)

gives 30

should obs.get_pointings() fill them?

Anyway, if I allocate and fill them with the output of obs.get_pointings, still I get an error when I run lbs.make_bin_map

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-44-381c5a54bdf2> in <module>
----> 1 m=lbs.make_bin_map([obs], nsideout)

~/Documents/Universita/litebird/simteam/codes/hwp/litebird_sim/litebird_sim/mapping.py in make_bin_map(obss, nside)
     70 
     71     for obs in obss:
---> 72         _accumulate_map_and_info(obs.tod, obs.pixel, obs.psi, info)
     73 
     74     if all([obs.comm is None for obs in obss]) or not mpi.MPI_ENABLED:

~/Library/Caches/pypoetry/virtualenvs/litebird-sim-iPzjGDqs-py3.7/lib/python3.7/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~/Library/Caches/pypoetry/virtualenvs/litebird-sim-iPzjGDqs-py3.7/lib/python3.7/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~/Library/Caches/pypoetry/virtualenvs/litebird-sim-iPzjGDqs-py3.7/lib/python3.7/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array(float64, 3d, C), float64)
 
There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(float64, 3d, C), float64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 162.
    With argument(s): '(array(float64, 3d, C), float64)':
   Rejected as the implementation raised a specific error:
     TypeError: unsupported array index type float64 in [float64]
  raised from /Users/luca/Library/Caches/pypoetry/virtualenvs/litebird-sim-iPzjGDqs-py3.7/lib/python3.7/site-packages/numba/core/typing/arraydecl.py:69

During: typing of intrinsic-call at /Users/luca/Documents/Universita/litebird/simteam/codes/hwp/litebird_sim/litebird_sim/mapping.py (22)

File "../codes/hwp/litebird_sim/litebird_sim/mapping.py", line 22:
def _accumulate_map_and_info(tod, pix, psi, info):
    <source elided>
        sin = np.sin(2 * a)
        info_pix = info[p]
        ^

**Comment by dpole** [comment]
The Traceback is quite misleading. I think that problem is that `pixel`somehow contains floats, but can't say how and why from what you said.

About what obs.get_pointings does, I agree it is not transparent. It would be clear if the method was an external function and the user assigned the output to the proper attributes of obs.

**Comment by paganol** [comment]
thanks! Allocating obs.pixel as integer solved this issue. Still the role of get_pointings should be discussed

**Comment by ziotom78** [comment]
Following the discussion we had during the last telecon, @mreineck suggested to call `obs.get_pointings` on the fly, i.e., only when these pointings are actually requested. This would permit to save memory (pointing information is very large) at the expense of a slight delay in computational time, which is however going to be negligible:

-   On my laptop it takes ~0.15 s to generate one day of pointing angles at full sampling rate;

-   Converting pointing angles into Heapix pixel indices requires an even smaller amount of time (~0.02 s).

**Comment by dpole** [comment]
Keep in mind though that an iterative map-making solver would compute it at every iteration. Not sure it is a game-changer, it depends on the application.

**Comment by ziotom78** [comment]
> Keep in mind though that an iterative map-making solver would compute it at every iteration. Not sure it is a game-changer, it depends on the application.

Sure, but if this is an issue, the code can keep a local copy of the pixel indices within the CG loop.

**Comment by mreineck** [comment]
I agree that caching can (and probably should) be done if performance is absolutely crucial.
However, there is still quite some optimization potential in the pointing calculation routines: we can parallelize them, and the algorithm can most likely be tweaked some more.

@ziotom78, can you give a rough estimate how many pointings were generated during the 0.15 seconds you measured?

**Comment by ziotom78** [comment]
I generated one quaternion every minute, which corresponds to 1440 quaternions/day.

P.S. I just realized that I used half the nominal LiteBIRD sampling frequency, so the time spent in generating the pointings should be doubled (0.3 s/day). However, I believe my point still stands.

**Comment by mreineck** [comment]
Sorry, I meant to ask how many interpolated quaternions were generated, or indirectly what the sampling frequency was ... I'm not completely up to date concerning LiteBIRD instrument parameters.

**Comment by ziotom78** [comment]
Ah, ok, I interpolated 10 quaternions/sec out of one quaternion every minute.

**Comment by mreineck** [comment]
OK, so 864000 quaternions in 0.15s, or 5.7 million per second. Not too bad, but could be better - I'll have a look.
In any case, I'll add an optional `nthreads` parameter which allows running the interpolation in parallel.

**Comment by mreineck** [comment]
One more question: did you do this in one call to the `get_rotated_quaternions` function for each day, or in several? If the latter, how many?

**Comment by mreineck** [comment]
OK, thanks!

**Comment by dpole** [comment]
A side comment on the `nthreads` parameter, shall we define a coherent way of parallelizing code? For example, what do you think about getting this info from `OMP_NUM_THREADS`?

**Comment by mreineck** [comment]
I wouldn't access `OMP_NUM_THREADS` at the lowest level, i.e. whenever a loop needs parallelizing. Depending on how the code parts are assembled, it could happen that parallelizable regions are within other parallelizable regions, and in that case the programmer has to decide what should happen.
But it should be fine to use `OMP_NUM_THREADS` as a vehicle to tell an entire simulation job how many threads it may use overall. It's a bit misleading (since parallelization will happen without using OpenMP in most cases), but people are used to this parameter ...

**Comment by mreineck** [comment]
Not sure what's the difference, but I get over 20 million interpolations per second per core on my (fairly old) laptop.
I'm using this script:

```
import ducc0.pointingprovider as pp
import numpy as np
import time

t0 = 0
size = 1000
fct = 10000
freq = 1
rng = np.random.default_rng(42)
quat = rng.uniform(-.5, .5, (size, 4))
prov = pp.PointingProvider(t0, freq, quat)
rquat = np.array([0., 0., 0., 1.])  # a non-rotating quaternion
tx=time.time()
quat2 = prov.get_rotated_quaternions(t0, freq*2*fct, rquat, nval=size*fct)
print("time to calculate 10 million interpolated quaternions:", time.time()-tx)
```
```
martin@debian:~/codes/ducc$ python3 pointing_bench.py 
time to calculate 10 million interpolated quaternions: 0.4677278995513916
```

This is roughly the number I would have expected, and is much more in line with the `ang2pix` timing reported by @ziotom78. I'm not sure what's going wrong here.

**Comment by ziotom78** [comment]
> I'm not sure what's going wrong here.

The point is that `Observation.get_pointings` is creating a new `np.array` by [assembling all the interpolated quaternions](https://github.com/litebird/litebird_sim/blob/master/litebird_sim/observations.py#L578-L589) for every detector. If I run the test by directly calling `get_detector_quats` (and thus avoiding the allocation), I get similar results as yours, @mreineck .

It should be trivial to optimize the method `Observation.get_det2ecl_quaternions`.
