### ISSUE TITLE
Update the list of authors

### ISSUE THREAD

**Issue by ziotom78** [litebird/litebird_sim#85]
File `pyproject.toml` should be updated with the list of people that want to be mentioned in the PyPI (Python Package Index) entry for the LiteBIRD Simulation Framework. Currently there are only two entries:

```toml
authors = [
	"The LiteBIRD Simulation Team",
	"Maurizio Tomasi <maurizio.tomasi@unimi.it>",
]
```

but the plan is to make the generic item `The LiteBIRD Simulation Team` disappear and have the proper list of authors listed here. Whoever wants to be listed, please modify the file/open a PR and add your name and email to the file. You can make this change within the browser using this link: https://github.com/litebird/litebird_sim/blob/master/pyproject.toml . Click on the pencil icon on the topright corner of the file to edit it:

![litebird_sim](https://user-images.githubusercontent.com/377795/103914379-06c48f80-510a-11eb-8313-d9fdcb8525e6.png)

Please keep alphabetical order!

N.B. It is not necessary that you contributed to this very repository to be listed as an author, nor that you are part of the Simulation Team! If you contributed in some way to the overall effort, you are entitled to opt in.

**Comment by dpole** [comment]
I added my name. I am not sure there was an order. Looking at the names already there, the only I could think of was alphabetic by Family name. Please feel free to reshuffle according to any criterion.

**Comment by ziotom78** [comment]
> alphabetic by Family name

That's right. Thanks!
